apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterresourceoverrides.operator.autoscaling.openshift.io
spec:
  conversion:
    strategy: None
  group: operator.autoscaling.openshift.io
  scope: Cluster
  names:
    plural: clusterresourceoverrides
    singular: clusterresourceoverride
    kind: ClusterResourceOverride
    listKind: ClusterResourceOverrideList
    shortNames:
    - cro
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        description: Allows cluster administrator to control the level of overcommit and manage container density on nodes.
        properties:
          spec:
            type: object
            description: Spec for a ClusterResourceOverride.
            properties:
              podResourceOverride:
                type: object
                description: Configuration for Pod resource overrides.
                properties:
                  spec:
                    type: object
                    description: Spec for Pod resource overrides.
                    properties:
                      forceSelinuxRelabel:
                        type: boolean
                        description: (optional, false) Enable the Selinux relabelling fix.
                      memoryRequestToLimitPercent:
                        type: integer
                        description: (optional, 1-100) If a container memory limit has been specified or defaulted, the memory request is overridden to this percentage of the limit.
                        minimum: 1
                        maximum: 100
                      cpuRequestToLimitPercent:
                        type: integer
                        description: (optional, 1-100) If a container CPU limit has been specified or defaulted, the CPU request is overridden to this percentage of the limit.
                        minimum: 1
                        maximum: 100
                      limitCPUToMemoryPercent:
                        type: integer
                        description: (optional, positive integer) If a container memory limit has been specified or defaulted, the CPU limit is overridden to a percentage of the memory limit, with a 100 percentage scaling 1Gi of RAM to equal 1 CPU core. This is processed prior to overriding CPU request (if configured).
                        minimum: 0
              deploymentOverrides:
                type: object
                description: Deployment overrides for ClusterResourceOverrides.
                properties:
                  nodeSelector:
                    type: object
                    description: (optional) NodeSelector to apply to ClusterResourceOverrides deployments.
                    additionalProperties:
                      type: string
                  tolerations:
                    type: array
                    description: (optional) Tolerations to apply to ClusterResourceOverrides deployments.
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        value:
                          type: string
                        effect:
                          type: string
                        tolerationSeconds:
                          type: integer
                  replicas:
                    type: integer
                    description: (optional) Number of replicas for ClusterResourceOverrides deployments. This number must not exceed the number of nodes that can accommodate the replicas, considering tolerations, and node selectors.
                    minimum: 0
          status:
            type: object
            description: The status of the ClusterResourceOverride
            x-kubernetes-preserve-unknown-fields: true
